[env]
TERM = "alacritty"
WSLENV = "TERM/u"

[font]
normal = { family = "Iosevka Term", style = "Medium Extended" }
bold = { family = "Iosevka Term", style = "Bold Extended" }
italic = { family = "Iosevka Term", style = "Medium Italic Extended" }
bold_italic = { family = "Iosevka Term", style = "Bold Italic Extended" }
size = 12
offset = { x = 1, y = 0 }
glyph_offset = { x = 0, y = 0 }

[window]
dimensions = { columns = 80, lines = 25 }
resize_increments = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "bash", args = ["-l"] }
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

# rootloops.sh
# Sugar: 7
# Colors: 6
# Sogginess: 4
# Flavor: Classic
# Fruit: Blackberry
# Milk: No milk

[colors.primary]
background = '#07040d'
foreground = '#f4f2f9'

[colors.cursor]
text = '#07040d'
cursor = '#b2a2d1'

[colors.normal]
black = '#261d35'
red = '#d97780'
green = '#7aa860'
yellow = '#bc904f'
blue = '#6b9bd9'
magenta = '#b77ed1'
cyan = '#52a9a9'
white = '#b2a2d1'

[colors.bright]
black = '#584875'
red = '#e6949a'
green = '#8ebf73'
yellow = '#d3a563'
blue = '#88b1e5'
magenta = '#c899de'
cyan = '#63c0bf'
white = '#e5dff1'
