[env]
TERM = "alacritty"
WSLENV = "TERM/u"

[font]
normal = { family = "Pragmasevka", style = "Regular" }
bold = { family = "Pragmasevka", style = "Bold" }
italic = { family = "Pragmasevka", style = "Italic" }
bold_italic = { family = "Pragmasevka", style = "Bold Italic" }
size = 15
# windows/directwrite
offset = { x = 1, y = 2 }
glyph_offset = { x = 0, y = 0 }
# linux/freetype
#offset = { x = 0, y = 1 }
#glyph_offset = { x = 0, y = -1 }

[window]
dimensions = { columns = 80, lines = 25 }
resize_increments = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "bash", args = ["-l"] }
osc52 = "CopyPaste"

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

# Colors (Root Loops)
# via https://rootloops.sh?sugar=7&colors=6&sogginess=0&flavor=1&fruit=10&milk=0

[colors.primary]
background = '#060606'
foreground = '#f3f3f3'

[colors.cursor]
text = '#060606'
cursor = '#ababab'

[colors.normal]
black = '#222222'
red = '#d97780'
green = '#7aa860'
yellow = '#bc904f'
blue = '#6b9bd9'
magenta = '#b77ed1'
cyan = '#52a9a9'
white = '#ababab'

[colors.bright]
black = '#525252'
red = '#e6949a'
green = '#8ebf73'
yellow = '#d3a563'
blue = '#88b1e5'
magenta = '#c899de'
cyan = '#63c0bf'
white = '#e2e2e2'
